# Generated by Django 5.2.17 on 2026-09-27 16:35

import django.utils.timezone
from django.db import migrations, models

from commerce_core.platform.db.grants import ProtectTable

# Web and job read the migration history (the release step's version checks
# do too) but never write it.
PROTECT_MIGRATION_HISTORY = (
    "REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON django_migrations FROM commerce_web, commerce_job"
)
UNPROTECT_MIGRATION_HISTORY = (
    "GRANT INSERT, UPDATE, DELETE ON django_migrations TO commerce_web, commerce_job"
)


def seed_kill_switch(apps, schema_editor):
    RuntimeSetting = apps.get_model("platform", "RuntimeSetting")
    RuntimeSetting.objects.get_or_create(
        kind="checkout_kill_switch", provider_key=None, defaults={"enabled": False}
    )


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RuntimeSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("checkout_kill_switch", "Checkout Kill Switch"),
                            ("provider_enabled", "Provider Enabled"),
                        ],
                        max_length=32,
                    ),
                ),
                ("provider_key", models.CharField(blank=True, max_length=64, null=True)),
                ("enabled", models.BooleanField()),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("kind__in", ["checkout_kill_switch", "provider_enabled"])
                        ),
                        name="runtimesetting_kind_allowed",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("kind", "checkout_kill_switch"), ("provider_key__isnull", True)
                            ),
                            models.Q(("kind", "provider_enabled"), ("provider_key__isnull", False)),
                            _connector="OR",
                        ),
                        name="runtimesetting_provider_key_pairing",
                    ),
                    models.UniqueConstraint(
                        fields=("kind", "provider_key"),
                        name="runtimesetting_kind_provider_uniq",
                        nulls_distinct=False,
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SettingChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("kind", models.CharField(max_length=32)),
                ("provider_key", models.CharField(blank=True, max_length=64, null=True)),
                ("before", models.BooleanField()),
                ("after", models.BooleanField()),
                ("actor_type", models.CharField(max_length=20)),
                ("actor_id", models.CharField(max_length=64)),
                ("reason", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("actor_type__in", ["staff", "customer", "system", "provider_event"])
                        ),
                        name="settingchange_actor_type_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("reason", ""), _negated=True),
                        name="settingchange_reason_required",
                    ),
                ],
            },
        ),
        ProtectTable(model_name="SettingChange"),
        migrations.RunSQL(PROTECT_MIGRATION_HISTORY, UNPROTECT_MIGRATION_HISTORY),
        migrations.RunPython(seed_kill_switch, migrations.RunPython.noop),
    ]
