# Generated by Django 5.2.17 on 2026-09-27 16:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platform", "0002_jobs"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=64)),
                (
                    "severity",
                    models.CharField(
                        choices=[("critical", "Critical"), ("warning", "Warning")], max_length=10
                    ),
                ),
                ("subject_type", models.CharField(max_length=64)),
                ("subject_id", models.CharField(max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("acknowledged", "Acknowledged"),
                            ("resolved", "Resolved"),
                        ],
                        default="open",
                        max_length=15,
                    ),
                ),
                ("context", models.JSONField(blank=True, default=dict)),
                ("first_raised_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_raised_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("raise_count", models.PositiveIntegerField(default=1)),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledged_by_type", models.CharField(blank=True, max_length=20)),
                ("acknowledged_by_id", models.CharField(blank=True, max_length=64)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_by_type", models.CharField(blank=True, max_length=20)),
                ("resolved_by_id", models.CharField(blank=True, max_length=64)),
            ],
            options={
                "indexes": [
                    models.Index(
                        condition=models.Q(("notified_at__isnull", True)),
                        fields=["notified_at"],
                        name="alert_unnotified",
                    ),
                    models.Index(fields=["status", "severity"], name="alert_status_severity"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "resolved"), _negated=True),
                        fields=("code", "subject_type", "subject_id"),
                        name="alert_one_open_per_subject",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("severity__in", ["critical", "warning"])),
                        name="alert_severity_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["open", "acknowledged", "resolved"])),
                        name="alert_status_valid",
                    ),
                ],
            },
        ),
    ]
