# Generated by Django 5.2.17 on 2026-09-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platform", "0003_alert"),
    ]

    operations = [
        migrations.CreateModel(
            name="RateLimitCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("policy", models.CharField(max_length=64)),
                ("principal_hash", models.CharField(max_length=64)),
                ("window_start", models.DateTimeField()),
                ("count", models.PositiveIntegerField()),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "indexes": [models.Index(fields=["expires_at"], name="ratelimit_expires")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("policy", "principal_hash", "window_start"),
                        name="ratelimit_window_uniq",
                    )
                ],
            },
        ),
    ]
