# Generated by Django 5.2.17 on 2026-09-27 16:55

import django.utils.timezone
from django.db import migrations, models

from commerce_core.platform.db.grants import ProtectTable


class Migration(migrations.Migration):
    dependencies = [
        ("platform", "0004_ratelimit"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReleaseRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("core_version", models.CharField(max_length=32)),
                ("deployment_env", models.CharField(max_length=20)),
                ("restore_point", models.CharField(blank=True, max_length=255)),
                ("restore_point_verified", models.BooleanField(default=False)),
                ("destructive_migrations", models.JSONField(blank=True, default=list)),
                ("applied_migrations", models.JSONField(blank=True, default=list)),
                ("applied_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "abstract": False,
            },
        ),
        ProtectTable(model_name="ReleaseRecord"),
        # Only the release step, as the migration role, writes release history (D6, W5).
        migrations.RunSQL(
            "REVOKE INSERT ON platform_releaserecord FROM commerce_web, commerce_job",
            "GRANT INSERT ON platform_releaserecord TO commerce_web, commerce_job",
        ),
    ]
