# Generated by Django 5.2.17 on 2026-09-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorePermissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("collect_cash", "Collect COD cash and record offline refund payouts"),
                    ("request_refund", "Request a refund of a staff-chosen amount"),
                    ("approve_refund", "Approve a refund (second approval)"),
                    ("approve_cancellation", "Approve a cancellation"),
                    ("adjust_stock", "Adjust stock"),
                    ("resolve_review", "Resolve a payment review case"),
                    ("manage_returns", "Manage returns"),
                    ("change_address", "Change a shipping address"),
                    ("create_shipment", "Create a shipment"),
                    ("record_delivery", "Record a courier outcome"),
                    ("record_receipt", "Record goods received back"),
                    ("view_payment_events", "View raw payment events"),
                    ("manage_settings", "Change runtime settings"),
                ],
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
