# Generated by Django 5.2.17 on 2026-09-27 16:21

from django.db import migrations, models

from commerce_core.platform.db.grants import ProtectTable


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppendOnlyProbe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("note", models.CharField(max_length=50)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GovernedProbe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("amount", models.BigIntegerField()),
                ("status", models.CharField(max_length=20)),
            ],
            options={
                "abstract": False,
            },
        ),
        ProtectTable(model_name="AppendOnlyProbe"),
        ProtectTable(model_name="GovernedProbe", update_fields=("status",)),
    ]
