# Generated by Django 5.2.17 on 2026-09-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UniqueProbe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("other", models.CharField(max_length=20)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("code",), name="testapp_uniqueprobe_code_uniq"),
                    models.UniqueConstraint(
                        fields=("other",), name="testapp_uniqueprobe_other_uniq"
                    ),
                ],
            },
        ),
    ]
