# Generated by Django 5.2.17 on 2026-09-27 16:40

from django.db import migrations, models

import commerce_core.platform.ids
import commerce_core.platform.money


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0003_lockprobe"),
    ]

    operations = [
        migrations.CreateModel(
            name="MoneyProbe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("amount", commerce_core.platform.money.MoneyAmountField()),
                ("currency", commerce_core.platform.money.CurrencyField()),
            ],
        ),
        migrations.CreateModel(
            name="PageProbe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        default=commerce_core.platform.ids.new_public_id, max_length=16, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("name", models.CharField(max_length=50)),
                ("category", models.CharField(max_length=20)),
                ("owner", models.CharField(default="alice", max_length=20)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["created_at", "public_id"], name="pageprobe_created_pub"),
                    models.Index(fields=["name", "public_id"], name="pageprobe_name_pub"),
                    models.Index(fields=["category"], name="pageprobe_category"),
                ],
            },
        ),
    ]
